shivamyadavrgipt/Social_media_management

src/App.jsx, src/pages/settings.jsx
Now the link is working
@shivamyadavrgipt  Please check 
Here I have changed the name of a file so it may fail in deployment.
settings.jsx  ==> Settings.jsx
https://github.com/user-attachments/assets/6e50e1e6-c77e-4404-af26-9d066c39cc74
=> fix the link

index.html
#22 
Added a chatbot powered by AI for all sorts of queries related to the website
=> Added a CHATBOT for the Social media management 

homepage
Output for landing page:
Fix issue #103
=> Create landing page fix issue #103

src/App.jsx
This pull request fixes the #107 page reload issue.
The import of the Setting component was wrong.
=> Fixed page reload

package-lock.json, package.json, src/App.css, src/App.jsx, src/components/Navbar.css, src/components/Navbar.jsx, src/components/ThemeToggle.css, src/components/ThemeToggle.jsx, src/pages/Dashboard.css, src/pages/Dashboard.jsx
=> Update :- Light and Dark mode & Dashboard

index.html
Merge the PR and give a gssoc-ext and level2 label.
Thankyou !!
=> Changed Chatbot Position for Better UI 

package-lock.json, package.json, src/App.jsx, src/components/Navbar.jsx, src/pages/Newsletter.css, src/pages/Newsletter.jsx
https://www.loom.com/share/583f2a48d99e478a93a9e838ce85f927
=> I have added newsletter page in tool tab

CODE_OF_CONDUCT
As per the issue #131 
I have made all the required changes in following topics-
I have added following points-
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion
Also , I tried to make it more creative.
If any further changes required please tell me.
Fixes issue #131
=> Created CODE_OF_CONDUCT

.github/workflows/greetings.yml
**Fixed #73**
**Description:**
This pull request introduces a "Greetings" workflow, designed to automatically send a warm, customized welcome to users who open new issues or pull requests in this repository.
**Key Features:**
- **Automatic Greeting**: New contributors receive instant, personalized messages that acknowledge their efforts:
- **For Issues**: "👋 Hi @${{ github.actor }}! Thank you for opening an issue and contributing to our project. Your input is valuable to us, and the team will review it soon. We appreciate your patience!"
- **For Pull Requests**: "🎉 Hi @${{ github.actor }}! Thank you for your pull request—your work brings us closer to our goals! A maintainer will review your submission shortly. We’re grateful for your effort and commitment."
**Implementation Details:**
- …
=> Fixed: "Greetings" workflow, designed to automatically send a warm,  welcome to users who open new issues or pull requests in this repository.

src/App.jsx, src/pages/PreLoader.jsx, src/pages/Preloader.css
Solved :
Issue no #147 
https://github.com/user-attachments/assets/2aa0e3ca-828f-4ff4-97b6-89d469061cb8
=> Adding animeted Pre Loader

src/index.css, src/pages/Contributors.css, src/pages/Contributors.jsx
https://www.loom.com/share/a809a70d83d84d619e3e27a73b0e1786
If we tap on any of profile it will redirect to their GitHub profile
=> I have added dynamic contributors page to fetch data

src/components/Navbar.jsx
Worked with the responsiveness of header issue #157
=> made the header reposnive 

src/pages/Dashboard.jsx
Reverts shivamyadavrgipt/Social_media_management#169
=> Revert "Update Dashboard.jsx"

src/components/Footer.jsx
changed the twitter icon using font awesome website.
fixed issue #174
=> changed the twitter icon in navbar

package-lock.json, package.json, src/pages/Dashboard.jsx
- Purpose: Resolves a 404 error when loading the Dashboard page.
- Issue Reference: Closes #178 
- Changes:
Done some changes in the Code where the modules are imported and Routed them accordingly.
- Testing:
Verified Dashboard loads successfully across multiple user accounts.
Confirmed no impact on other routes and verified successful page load after deployment.
- Impact: This fix resolves the broken Dashboard link, allowing users to access the page as expected. There are no breaking changes.
Snapshot after fixing the issue :
=> Fix #178 : 404 Error on Dashboard Page Load

src/components/Navbar.jsx
**Description:**
This PR addresses several issues with the navbar on the landing page, specifically focusing on icon misrotation, sizing, and hover animations. The following changes have been implemented:
- **Navbar Icon Misrotation:** Fixed the misrotation of the navbar icon that was present on the landing page.
- **Dropdown-Bug:** Earlier the icon rerotated back to unhovered state as soon as cursor got away from icon but now It stays in hovered state until dropdown closes. Thus improving the UX...
- **Icon Sizing:** Adjusted the sizing of the navbar icons for better alignment and visibility.
- **Hover Animations:** Enhanced the hover animations for navbar items to provide a smoother user experience.
- **Dynamic Rotation:** Added a `useEffect` hook to update the icon rotation based on …
=> Fix navbar animations: resolved hover effects, rotation, and sizing issues

src/pages/settings.css, src/pages/settings.jsx
Here are the screenshots of the udpated page
Here is the updated settings page hope you like it :)
=> Added Settings Page

package-lock.json, package.json, src/App.jsx, src/components/TopButton.jsx, src/pages/LandingPage.jsx
I add the scroll to top button in this website
=> Add Scroll to top button

package-lock.json, package.json, src/components/Footer.jsx
**PR Title**: `style: Enhance footer design for improved aesthetics`
#207 
- Enhanced the footer design to make it more visually appealing and cohesive with the rest of the website.
- Added styling improvements, including colors, spacing, and alignment adjustments, to create a more polished look.
- Improved layout and design elements to make the footer more user-friendly and engaging.
These changes make the footer more attractive and provide a better user experience by creating a consistent and professional design across the site.
- Manually tested the new footer design on different screen sizes to ensure responsiveness and appearance consistency.
- Verified that all footer links and interactive elements work as expected after the redesign.
=> Enhance the footer

src/components/Footer.jsx, src/components/Navbar.jsx, src/pages/LandingPage.jsx, src/pages/Login.jsx, src/pages/SignUp.jsx
Added the backend routing for the signup
Added correct routing for login page
Old login page:
Updated login page:
Removed issues with the Landing Page
This error came when ran a newly synced fork... So removed the bugs from here as well and cleaned the code.
@shivamyadavrgipt I think this deserve a level3... pretty please :)
=> Removed Bugs (Signup, Login and Landing Page)
